name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: make
    
    - name: Simple Run 
      run: ./project1
      
    - name: Install Valgrind
      run: sudo apt install -y valgrind
      
    - name: Check Valgrind
      run: valgrind ./project1
      
    - name: Clean
      run: make clean
